### PR TITLE
Add basic auth BBG

### PR DESCRIPTION
**Pull request by isharak**

### CODE REVIEW

**Review by kasun04 — CHANGES_REQUESTED** [review]
Please resolve conflicts.

**Comment by pubudu91** [comment]
@isharak Is this PR still valid? If so, shall we resolve the conflicts and get this merged?

**Comment by ayomawdb** [comment]
Most of the suggested changes here are in the master branch and this PR heavily conflicts with the new syntax. 

We can close this PR and I will send a separate PR with any missing changes.

**Comment by anupama-pathirage** [comment]
Closing this PR for now as we are no longer actively maintaining this repo.

**Pull request closed without merging**
